const SOCKET_API_URL = "https://api.socket.tech/v2";
const MOST_VALUED_TOKENS = [
  "Aave",
  "Alongside Crypto Market Index",
  "Amp",
  "Aragon Network Token",
  "ApeCoin",
  "Balancer",
  "Band Protocol",
  "Bancor Network Token",
  "Coinbase Wrapped Staked ETH",
  "Compound",
  "Curve DAO Token",
  "Civic",
  "Dai Stablecoin",
  "district0x",
  "Dola USD Stablecoin",
  "Ethereum name Service",
  "Ethereum",
  "Frax",
  "Frax Shares",
  "Gnosis Token",
  "The Graph",
  "Instadapp",
  "Keep Network",
  "Kyber Network Crystal",
  "ChainLink Token",
  "LoopringCoin V2",
  "LUSD Stablecoin",
  "Decentraland",
  "Polygon",
  "Matic",
  "MCDEX Token",
  "MAGIC INTERNET MONEY",
  "Maker",
  "Melon",
  "Numeraire",
  "NuCypher",
  "OATH Token",
  "PENDLE",
  "Premia",
  "Republic Token",
  "Reputation Augur v2",
  "Rocket Pool ETH",
  "Synthetix Network Token",
  "sETH",
  "Storj Token",
  "Synth sUSD",
  "tBTC",
  "UMA Voting Token v1",
  "Uniswap",
  "USDCoin",
  "Tether USD",
  "Wrapped BTC",
  "Wrapped Ether",
  "Wrapped Staked ETH",
  "XSGD",
  "yearn finance",
  "0x Protocol Token",
];

export { SOCKET_API_URL, MOST_VALUED_TOKENS };
